# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(choices=[('K', '한식'), ('C', '중식'), ('J', '일식'), ('E', '유럽식')], max_length=1, verbose_name='음식'),
        ),
    ]
